In [ ]:
import numpy as np


In [ ]:
myarr=np.array([1,2,3,4444,5],np.int32)


In [ ]:
myarr
 

array([   1,    2,    3, 4444,    5], dtype=int32)

In [ ]:
myarr[1]

2

In [ ]:
myarr1=np.array([[1,2,3,4,5,6],[3,4,6,3,2,8]])

In [ ]:
myarr1[1m,2]

6

In [ ]:
myarr.shape


(5,)

In [ ]:
myarr1.shape

(2, 6)

In [ ]:
myarr.dtype

dtype('int32')

In [ ]:
myarr1.dtype

dtype('int64')

Array Creation : Conversion from other Python structures

In [ ]:
listarray=np.array([[1,23,4],[4,6,7],[1,0,8]])


In [ ]:
listarray


array([[ 1, 23,  4],
       [ 4,  6,  7],
       [ 1,  0,  8]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({12,3,6,9})

array({9, 3, 12, 6}, dtype=object)

Instrinsic numpy array (zeros etc)

In [ ]:
zeroarray=np.zeros((2,5))

In [ ]:
zeroarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeroarray.dtype

dtype('float64')

In [ ]:
zeroarray.shape

(2, 5)

In [ ]:
zeroarray.size

10

In [ ]:
rng1=np.arange(15)

In [ ]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:

lspace=np.linspace(1,5,6)
#returns array with 6 elements from 1 to 5 which are equaly spaced

In [ ]:
lspace

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [ ]:
emp=np.empty((4,6))
#returns array with random elements

In [ ]:
emp

array([[0.00000000e+000, 7.01573217e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.16251369e+180],
       [1.05776693e-153, 6.03461190e+151, 1.12949595e-095,
        1.67772392e+243, 1.16466606e-028, 4.90900643e+252],
       [1.94918511e-153, 3.00833776e+151, 9.03292974e+271,
        6.96411098e+252, 5.49740424e-095, 3.16251369e+180],
       [3.65588338e+233, 8.61882260e+183, 2.59050147e-144,
        1.16442250e-028, 6.79769037e-310, 0.00000000e+000]])

In [ ]:
emp_like=np.empty_like(lspace)

In [ ]:
emp_like

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [ ]:
ide=np.identity(3)

In [ ]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
myarr=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
myarr


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
myarr=myarr.reshape(6,2)
myarr

array([[ 1,  2],
       [ 3,  4],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
myarr=myarr.ravel()
myarr

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar
ar.sum(axis=0)
ar.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.ndim

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
one=np.array([1,2,3,4,5,6])

In [ ]:
one.argmax()#returns max element
one.argmin()
one.argsort()#sorts the array

5